default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: travel_journal_development

test:
  <<: *default
  database: travel_journal_test

production:
  <<: *default
  database: travel_journal_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
